[project]
name = "mock-monero"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fcmp",
    "monero",
]

[tool.uv.workspace]
members = ["fcmp", "monero"]

[tool.uv.sources]
monero = { workspace = true }
fcmp = { workspace = true }
